apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: skaffold-go-module
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
